trying to fix deploy x12

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -41,8 +41,8 @@ jobs:
 
       - name: Deploy to Elastic Beanstalk
         run: |
-        eb deploy || (echo "Deployment failed. Listing application versions." && aws elasticbeanstalk describe-application-versions --application-name ${{ secrets.EB_APPLICATION }})
+          eb deploy || (echo "Deployment failed. Listing application versions." && aws elasticbeanstalk describe-application-versions --application-name ${{ secrets.EB_APPLICATION }})
 
       - name: Check Environment Health
         run: |
-        eb health
+          eb health
